{
	"exception test": {
		"scope": "javascript,typescript",
		"prefix": "exception",
		"body": [
			"const suts = [].concat(",
			"  new Class(",
			"    { method () { throw new Error() } }",
			"  )",
			")",
			"for (const sut of suts) {",
			"  const promise = sut.method()",
			"  await expect(promise).rejects.toThrow()",
			"}"
		],
	}
}